add test files for container services

diff --git a/.github/actions/locust-run/action.yml b/.github/actions/locust-run/action.yml
--- a/.github/actions/locust-run/action.yml
+++ b/.github/actions/locust-run/action.yml
@@ -14,11 +14,17 @@ inputs:
     description: "How long to run for"
     required: false
     default: '60s'
+outputs:
+  json-cleaned:
+    description: "Whether the JSON is in a valid format or not now"
+    value: ${{ steps.json-cleaner.outputs.json-cleaned }}
+
 runs:
   using: 'composite'
   steps:
     # Run locust test and output results
     - name: Run locust test
+      id: locust-runner
       shell: bash
       run: |
         source .venv/bin/activate
@@ -30,7 +36,7 @@ runs:
 
         mkdir -p $LOG_DIR $HTML_DIR $CSV_DIR $JSON_DIR
 
-        echo "JSON_PATH=./jsonfiles/$CURR_TIME" >> $GITHUB_ENV
+        echo "JSON_DIR=$JSON_DIR" >> $GITHUB_ENV
         echo "CURR_TIME=$CURR_TIME" >> $GITHUB_ENV
 
         locust \
@@ -46,4 +52,31 @@ runs:
           --exit-code-on-error 1 \
           --only-summary | awk '/\[/{flag=1} flag; /\]/{flag=0; print}' > $JSON_DIR/$(echo $CURR_TIME).json
 
-        unset CURR_TIME LOG_DIR HTML_DIR CSV_DIR JSON_DIR
+        unset CURR_TIME LOG_DIR HTML_DIR CSV_DIR
+
+    # Clean JSON Data
+    - name: Clean locust output JSON data
+      id: json-cleaner
+      shell: bash
+      run: |
+        source .venv/bin/activate
+        BLUE="\033[34m"
+        RESET="\033[0m"
+        
+        if ! jq '.' $JSON_DIR/$(echo $CURR_TIME).json 2>/dev/null; then
+          echo -e "${BLUE}Invalid JSON detected!${RESET}"
+          sed -i '$d' $JSON_DIR/$(echo $CURR_TIME).json
+          if ! jq '.' $JSON_DIR/$(echo $CURR_TIME).json 2>/dev/null; then
+            echo -e "${BLUE}JSON still invalid!${RESET}"
+            echo "json-cleaned=false" >> $GITHUB_ENV
+            exit 1
+          else
+            echo -e "${BLUE}JSON is valid.${RESET}"
+            echo "json-cleaned=true" >> $GITHUB_ENV
+          fi
+        else
+          echo -e "${BLUE}JSON is valid.${RESET}"
+          echo "json-cleaned=true" >> $GITHUB_ENV
+        fi
+
+      continue-on-error: true
