add artifact upload

diff --git a/.github/workflows/job-artifacts.yml b/.github/workflows/job-artifacts.yml
--- a/.github/workflows/job-artifacts.yml
+++ b/.github/workflows/job-artifacts.yml
@@ -25,9 +25,6 @@ jobs:
           pip3 install --upgrade pip setuptools wheel
           pip3 install -r requirements.txt
 
-      - name: Install jq
-        run: sudo apt-get install jq
-
     # TODO: Need to add some flags that will generate csv files, html files, and log files. These will be uploaded as artifacts.
       - name: Run locust test
         run: |
@@ -42,6 +39,8 @@ jobs:
           mkdir -p $CSV_DIR
           mkdir -p $JSON_DIR
           
+          echo "JSON_PATH=./jsonfiles/$CURR_TIME" >> $GITHUB_ENV
+          
           locust \
             -f locustfiles/test.py \
             --users 25 \
@@ -55,9 +54,25 @@ jobs:
             --exit-code-on-error 1 \
             --only-summary | awk '/\[/{flag=1} flag; /\]/{flag=0; print}' > $JSON_DIR/$(echo $CURR_TIME).json
           
-          jq '.' $JSON_DIR/$(echo $CURR_TIME).json > $JSON_DIR/$(echo $CURR_TIME)_corrected.json
-          
-          unset CURR_TIME LOG_DIR HTML_DIR CSV_DIR JSON_DIR
+          unset CURR_TIME LOG_DIR HTML_DIR CSV_DIR
+
+      - name: Clean JSON data
+        run: |
+          if ! jq '.' $JSON_PATH/$(echo $CURR_TIME).json 2>/dev/null; then
+            echo "Invalid JSON detected!"
+            sed -i '$d' $JSON_PATH/$(echo $CURR_TIME).json
+            sed -i '$d' $JSON_PATH/$(echo $CURR_TIME).json
+            if ! jq '.' $JSON_PATH/$(echo $CURR_TIME).json 2>/dev/null; then
+              echo "JSON still invalid!"
+              exit 1
+            else
+              echo "JSON is valid."
+            fi
+          else
+            "JSON is valid."
+          fi
+
+        continue-on-error: true
 
       - name: Check if new files have been produced
         run: |
